// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect(1366, 738)
    await driver.findElement(By.css(".\\_blc_frm:nth-child(1) > label")).click()
    await driver.findElement(By.id("user_insc")).sendKeys("space_admin@esi.dz")
    await driver.findElement(By.id("mtpss")).sendKeys("adminadmin")
    await driver.findElement(By.id("cnt_to")).click()
    await driver.findElement(By.css("div:nth-child(1) > .\\_list_block_number .\\_page_link:nth-child(1) > span")).click()
    await driver.findElement(By.css(".\\_inptmsgenv")).click()
    {
      const element = await driver.findElement(By.css(".\\_inptmsgenv"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'hello word'}", element)
    }
    await driver.findElement(By.id("__inpttosent")).click()
    await driver.findElement(By.css(".\\_message_sent")).click()
    await driver.findElement(By.id("__inpttosent")).click()
    await driver.findElement(By.id("__inpttosent")).click()
    await driver.findElement(By.css(".click_show > img")).click()
    await driver.findElement(By.css(".name_option:nth-child(2) span")).click()
    await driver.findElement(By.id("user_insc")).click()
    await driver.findElement(By.id("user_insc")).sendKeys("space_admin@esi.dz")
    await driver.findElement(By.id("mtpss")).sendKeys("adminadmin")
    await driver.findElement(By.id("cnt_to")).click()
    await driver.findElement(By.css("div:nth-child(1) > .\\_list_block_number .\\_page_link:nth-child(1) > span")).click()
    {
      const element = await driver.findElement(By.css(".\\_pttmsg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".\\_cntrlbtmsg")).click()
    await driver.findElement(By.css(".\\_nmmsg > span")).click()
    await driver.findElement(By.id("__inpttosent")).click()
    {
      const element = await driver.findElement(By.id("__inpttosent"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'space_m.hamzaoui@esi.dz'}", element)
    }
    await driver.findElement(By.css(".\\_inptmsgenv")).click()
    {
      const element = await driver.findElement(By.css(".\\_inptmsgenv"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'mohamed'}", element)
    }
    await driver.findElement(By.css(".\\_elmfrmimg img")).click()
    await driver.findElement(By.id("addimage")).sendKeys("C:\\fakepath\\555.png")
    await driver.findElement(By.css(".\\_cnfsent > img")).click()
    await driver.findElement(By.css(".\\_clsmsg > span:nth-child(1)")).click()
    await driver.findElement(By.css(".\\_page_block:nth-child(2) .\\_page_link:nth-child(1) > span")).click()
    await driver.findElement(By.css(".\\_rglinfo")).click()
    await driver.findElement(By.css(".\\__btdwnld > img")).click()
    await driver.findElement(By.css(".\\__cntmsgslct > img")).click()
    await driver.findElement(By.css(".\\_page_bloc_drl:nth-child(1) .\\_page_link > span")).click()
    await driver.findElement(By.linkText("Gestion des étudiants")).click()
  })
})
